# 需要排除的测试文件
EXcluded_tests = {
    "tests/test_unified_report_service.py",
    "tests/core/test_edge_cases.py",
    "tests/core/agents/test_athena_advisor.py",
    "tests/core/agents/test_base.py",
    "tests/core/agents/test_example_agent.py",
    "tests/core/agents/test_factory.py",
    "tests/core/agents/test_xiaona_legal.py",
    "tests/core/agents/test_xiaonuo_coordinator.py",
    "tests/core/execution/test_performance.py",
    "tests/core/execution/test_shared_types.py",
    "tests/core/learning/integration/test_performance_stress.py",
    "tests/core/perception/test_factory.py",
    "tests/integration/test_agent_integrations.py",
    "tests/integration/test_end_to_end_collaboration.py",
    "tests/integration/test_legal_world_model.py",
    "tests/integration/core/intent/test_intent_integration.py",
    "tests/integration/core/intent/test_intent_refactoring.py",
    "tests/integration/learning/test_learning_api.py",
    "tests/integration/tools/test_integration.py",
    "tests/integration/tools/test_integration_simple.py",
    "tests/integration/tools/test_stress.py",
    "tests/legal_world_model/test_scenario_retriever.py",
    "tests/performance/test_performance_benchmarks.py",
    "tests/performance/tools/test_benchmark.py",
    "tests/performance/tools/test_concurrency.py",
    "tests/unit/test_legal_knowledge_graph.py",
    "tests/unit/test_unified_evaluation_framework.py",
    "tests/unit/test_xiaonuo_core.py",
    "tests/unit/communication/test_monitoring.py",
    "tests/unit/mcp/test_mcp_client_manager.py",
    "tests/unit/patent/test_claim_generator_v2.py",
    "tests/unit/production/core/learning/test_utils.py",
}

