#!/usr/bin/env python3
"""
生成法律世界模型数据量完整报告
"""
from datetime import datetime

print("=" * 80)
print("法律世界模型数据量完整报告")
print("=" * 80)
print(f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print()

print("## 📊 数据量统计\n")

print("### 1. PostgreSQL法律知识库（legal_world_model）")
print("-" * 80)
print("✅ **总计: 4,154,519条记录**")
print()
print("**主要数据表**:")
print("- patent_invalid_entities: 2,363,891行（专利无效实体）")
print("- judgment_entities: 891,659行（判决实体）")
print("- legal_articles_v2_embeddings: 295,810行（法律条文向量）")
print("- legal_articles_v2: 295,733行（法律条文原文）")
print("- patent_invalid_embeddings: 119,660行（专利无效向量）")
print("- judgment_relations: 45,770行（判决关系）")
print("- patent_invalid_decisions: 31,562行（专利无效决定）")
print("- 其他: 106,264行")
print()

print("### 2. Qdrant向量数据库")
print("-" * 80)
print("✅ **总计: 63,154条向量数据**")
print()
print("**主要集合**:")
print("- legal_knowledge: 40,050条（1024维）")
print("- invalidation_decisions: 17,034条（1024维）")
print("- baochen_wiki: 3,788条（1024维）")
print("- agent_memory_vectors: 2,212条（1024维）")
print("- 测试数据: 70条")
print()

print("### 3. Neo4j知识图谱")
print("-" * 80)
print("❌ **当前: 0节点，0关系**")
print()
print("**历史数据（2024-04-17验证）**:")
print("- 总节点数: 397,064个")
print("- 总关系数: 64,607个")
print("- ScenarioRule（场景规则）: 29个")
print()
print("**问题**: Docker数据卷在2024-04-18被重置，数据丢失")
print()

print("## 📈 数据完整性分析\n")

print("### PostgreSQL向量数据 vs Qdrant向量数据")
print("-" * 80)
print("**PostgreSQL中的向量数据**:")
print("- legal_articles_v2_embeddings: 295,810条")
print("- patent_invalid_embeddings: 119,660条")
print("- judgment_embeddings: 20,478条")
print("- patent_judgment_vectors: 17,388条")
print("- **PostgreSQL向量总计: 453,336条**")
print()
print("**Qdrant中的向量数据**:")
print("- legal_knowledge: 40,050条")
print("- invalidation_decisions: 17,034条")
print("- baochen_wiki: 3,788条")
print("- agent_memory_vectors: 2,212条")
print("- **Qdrant向量总计: 63,084条**")
print()
print("**差异**: PostgreSQL有45.3万条向量，Qdrant只有6.3万条")
print("**说明**: Qdrant只包含部分数据，可能需要同步")
print()

print("### PostgreSQL实体数据 vs Neo4j节点数据")
print("-" * 80)
print("**PostgreSQL中的实体数据**:")
print("- patent_invalid_entities: 2,363,891个")
print("- judgment_entities: 891,659个")
print("- **PostgreSQL实体总计: 3,255,550个**")
print()
print("**Neo4j中的节点数据（历史）**:")
print("- 总节点数: 397,064个（2024-04-17）")
print("- 总节点数: 0个（2024-04-18当前）")
print()
print("**差异**: PostgreSQL有325万个实体，历史Neo4j只有39万个节点")
print("**说明**: ")
print("1. Neo4j只导入了部分实体数据")
print("2. 4月18日Docker卷重置，Neo4j数据丢失")
print("3. 需要从PostgreSQL重新构建知识图谱")
print()

print("## 💡 结论和建议\n")

print("**当前数据状态**:")
print("✅ PostgreSQL: 415万条记录（完整）")
print("✅ Qdrant: 6.3万条向量（部分）")
print("❌ Neo4j: 0节点（数据丢失）")
print()
print("**总数据量**: 约422万条记录")
print()
print("**建议**:")
print("1. ⚠️  从PostgreSQL重新构建Neo4j知识图谱")
print("   - 导入patent_invalid_entities（236万实体）")
print("   - 导入judgment_entities（89万实体）")
print("   - 导入judgment_relations（4.5万关系）")
print()
print("2. 📊 同步PostgreSQL向量数据到Qdrant")
print("   - legal_articles_v2_embeddings（29.5万）")
print("   - patent_invalid_embeddings（11.9万）")
print()
print("3. 💾 建立定期备份机制")
print("   - Neo4j数据卷备份")
print("   - 避免Docker卷被重置")
print()

print("=" * 80)
