[server]
# HTTP端口
http_port = 3000

# 绑定地址
http_addr = 127.0.0.1

[security]
# 初始管理员密码
admin_user = admin
admin_password = admin

# 禁用注册（个人使用）
disable_gravatar = true

[database]
# 数据库类型
type = sqlite3

# 数据库路径
path = data/grafana/grafana.db

[log]
# 日志级别
mode = file

# 日志文件
file_path = data/grafana/logs

# 日志级别
level = Info

[dashboards]
# 默认主面板
default_home_dashboard_path = configs/grafana_dashboard.json

[users]
# 默认主题
default_theme = dark

[auth.anonymous]
# 启用匿名访问（个人使用可选）
enabled = false

[session]
# 会话提供者
provider = file

# 会话文件路径
provider_config = data/grafana/sessions
