// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/agent_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 响应类型
type ResponseType int32

const (
	ResponseType_PROGRESS ResponseType = 0 // 进度更新
	ResponseType_PARTIAL  ResponseType = 1 // 部分结果
	ResponseType_FINAL    ResponseType = 2 // 最终结果
	ResponseType_ERROR    ResponseType = 3 // 错误
)

// Enum value maps for ResponseType.
var (
	ResponseType_name = map[int32]string{
		0: "PROGRESS",
		1: "PARTIAL",
		2: "FINAL",
		3: "ERROR",
	}
	ResponseType_value = map[string]int32{
		"PROGRESS": 0,
		"PARTIAL":  1,
		"FINAL":    2,
		"ERROR":    3,
	}
)

func (x ResponseType) Enum() *ResponseType {
	p := new(ResponseType)
	*p = x
	return p
}

func (x ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_service_proto_enumTypes[0].Descriptor()
}

func (ResponseType) Type() protoreflect.EnumType {
	return &file_proto_agent_service_proto_enumTypes[0]
}

func (x ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseType.Descriptor instead.
func (ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

// 任务请求
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // "xiaona", "xiaonuo", "yunxi"
	Scenario      string                 `protobuf:"bytes,3,opt,name=scenario,proto3" json:"scenario,omitempty"`                    // "patent_search", "legal_analysis", etc.
	UserInput     string                 `protobuf:"bytes,4,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	Context       map[string]string      `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProjectPath   string                 `protobuf:"bytes,6,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"` // 0-10, 默认5
	Timeout       int32                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`   // 超时时间（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *TaskRequest) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *TaskRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *TaskRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *TaskRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *TaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// 任务响应（流式）
type TaskResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	TaskId    string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentType string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Type      ResponseType           `protobuf:"varint,3,opt,name=type,proto3,enum=athena.agent.v1.ResponseType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TaskResponse_Progress
	//	*TaskResponse_PartialResult
	//	*TaskResponse_FinalResult
	//	*TaskResponse_Error
	Payload       isTaskResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *TaskResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_PROGRESS
}

func (x *TaskResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskResponse) GetPayload() isTaskResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *TaskResponse) GetPartialResult() string {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_PartialResult); ok {
			return x.PartialResult
		}
	}
	return ""
}

func (x *TaskResponse) GetFinalResult() string {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_FinalResult); ok {
			return x.FinalResult
		}
	}
	return ""
}

func (x *TaskResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*TaskResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTaskResponse_Payload interface {
	isTaskResponse_Payload()
}

type TaskResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

type TaskResponse_PartialResult struct {
	PartialResult string `protobuf:"bytes,6,opt,name=partial_result,json=partialResult,proto3,oneof"`
}

type TaskResponse_FinalResult struct {
	FinalResult string `protobuf:"bytes,7,opt,name=final_result,json=finalResult,proto3,oneof"`
}

type TaskResponse_Error struct {
	Error *Error `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

func (*TaskResponse_Progress) isTaskResponse_Payload() {}

func (*TaskResponse_PartialResult) isTaskResponse_Payload() {}

func (*TaskResponse_FinalResult) isTaskResponse_Payload() {}

func (*TaskResponse_Error) isTaskResponse_Payload() {}

// 进度更新
type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    int32                  `protobuf:"varint,1,opt,name=percentage,proto3" json:"percentage,omitempty"` // 0-100
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentStep   string                 `protobuf:"bytes,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProgressUpdate) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *ProgressUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProgressUpdate) GetCurrentStep() string {
	if x != nil {
		return x.CurrentStep
	}
	return ""
}

func (x *ProgressUpdate) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ProgressUpdate) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// 错误信息
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Agent状态请求
type AgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentType     string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusRequest.ProtoReflect.Descriptor instead.
func (*AgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *AgentStatusRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

// Agent状态响应
type AgentStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentType      string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	IsHealthy      bool                   `protobuf:"varint,2,opt,name=is_healthy,json=isHealthy,proto3" json:"is_healthy,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "idle", "busy", "error"
	CurrentTasks   int32                  `protobuf:"varint,4,opt,name=current_tasks,json=currentTasks,proto3" json:"current_tasks,omitempty"`
	TotalCompleted int64                  `protobuf:"varint,5,opt,name=total_completed,json=totalCompleted,proto3" json:"total_completed,omitempty"`
	TotalFailed    int64                  `protobuf:"varint,6,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	CpuUsage       float64                `protobuf:"fixed64,7,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage    float64                `protobuf:"fixed64,8,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,9,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveTaskIds  []string               `protobuf:"bytes,10,rep,name=active_task_ids,json=activeTaskIds,proto3" json:"active_task_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusResponse.ProtoReflect.Descriptor instead.
func (*AgentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStatusResponse) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentStatusResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *AgentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatusResponse) GetCurrentTasks() int32 {
	if x != nil {
		return x.CurrentTasks
	}
	return 0
}

func (x *AgentStatusResponse) GetTotalCompleted() int64 {
	if x != nil {
		return x.TotalCompleted
	}
	return 0
}

func (x *AgentStatusResponse) GetTotalFailed() int64 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *AgentStatusResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentStatusResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentStatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AgentStatusResponse) GetActiveTaskIds() []string {
	if x != nil {
		return x.ActiveTaskIds
	}
	return nil
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentType     string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok", "error"
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 批量请求
type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskRequest         `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Concurrency   int32                  `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"` // 并发数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *BatchRequest) GetTasks() []*TaskRequest {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *BatchRequest) GetConcurrency() int32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

// 批量响应
type BatchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BatchId string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TaskId  string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type    ResponseType           `protobuf:"varint,3,opt,name=type,proto3,enum=athena.agent.v1.ResponseType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BatchResponse_Progress
	//	*BatchResponse_FinalResult
	//	*BatchResponse_Error
	Payload       isBatchResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *BatchResponse) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BatchResponse) GetType() ResponseType {
	if x != nil {
		return x.Type
	}
	return ResponseType_PROGRESS
}

func (x *BatchResponse) GetPayload() isBatchResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BatchResponse) GetProgress() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Payload.(*BatchResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *BatchResponse) GetFinalResult() string {
	if x != nil {
		if x, ok := x.Payload.(*BatchResponse_FinalResult); ok {
			return x.FinalResult
		}
	}
	return ""
}

func (x *BatchResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*BatchResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isBatchResponse_Payload interface {
	isBatchResponse_Payload()
}

type BatchResponse_Progress struct {
	Progress *ProgressUpdate `protobuf:"bytes,4,opt,name=progress,proto3,oneof"`
}

type BatchResponse_FinalResult struct {
	FinalResult string `protobuf:"bytes,5,opt,name=final_result,json=finalResult,proto3,oneof"`
}

type BatchResponse_Error struct {
	Error *Error `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*BatchResponse_Progress) isBatchResponse_Payload() {}

func (*BatchResponse_FinalResult) isBatchResponse_Payload() {}

func (*BatchResponse_Error) isBatchResponse_Payload() {}

// 取消请求
type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *CancelRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 取消响应
type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *CancelResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_agent_service_proto protoreflect.FileDescriptor

const file_proto_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/agent_service.proto\x12\x0fathena.agent.v1\"\xda\x02\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x1a\n" +
	"\bscenario\x18\x03 \x01(\tR\bscenario\x12\x1d\n" +
	"\n" +
	"user_input\x18\x04 \x01(\tR\tuserInput\x12C\n" +
	"\acontext\x18\x05 \x03(\v2).athena.agent.v1.TaskRequest.ContextEntryR\acontext\x12!\n" +
	"\fproject_path\x18\x06 \x01(\tR\vprojectPath\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x18\n" +
	"\atimeout\x18\b \x01(\x05R\atimeout\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x02\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.athena.agent.v1.ResponseTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12=\n" +
	"\bprogress\x18\x05 \x01(\v2\x1f.athena.agent.v1.ProgressUpdateH\x00R\bprogress\x12'\n" +
	"\x0epartial_result\x18\x06 \x01(\tH\x00R\rpartialResult\x12#\n" +
	"\ffinal_result\x18\a \x01(\tH\x00R\vfinalResult\x12.\n" +
	"\x05error\x18\b \x01(\v2\x16.athena.agent.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x92\x02\n" +
	"\x0eProgressUpdate\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x05R\n" +
	"percentage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\tR\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\x12F\n" +
	"\adetails\x18\x05 \x03(\v2,.athena.agent.v1.ProgressUpdate.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"3\n" +
	"\x12AgentStatusRequest\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\"\xeb\x02\n" +
	"\x13AgentStatusResponse\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\x12\x1d\n" +
	"\n" +
	"is_healthy\x18\x02 \x01(\bR\tisHealthy\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_tasks\x18\x04 \x01(\x05R\fcurrentTasks\x12'\n" +
	"\x0ftotal_completed\x18\x05 \x01(\x03R\x0etotalCompleted\x12!\n" +
	"\ftotal_failed\x18\x06 \x01(\x03R\vtotalFailed\x12\x1b\n" +
	"\tcpu_usage\x18\a \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\b \x01(\x01R\vmemoryUsage\x12%\n" +
	"\x0euptime_seconds\x18\t \x01(\x03R\ruptimeSeconds\x12&\n" +
	"\x0factive_task_ids\x18\n" +
	" \x03(\tR\ractiveTaskIds\"\xd9\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.athena.agent.v1.HeartbeatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x01\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12L\n" +
	"\bmetadata\x18\x03 \x03(\v20.athena.agent.v1.HeartbeatResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\fBatchRequest\x122\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1c.athena.agent.v1.TaskRequestR\x05tasks\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\x05R\vconcurrency\"\x95\x02\n" +
	"\rBatchResponse\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.athena.agent.v1.ResponseTypeR\x04type\x12=\n" +
	"\bprogress\x18\x04 \x01(\v2\x1f.athena.agent.v1.ProgressUpdateH\x00R\bprogress\x12#\n" +
	"\ffinal_result\x18\x05 \x01(\tH\x00R\vfinalResult\x12.\n" +
	"\x05error\x18\x06 \x01(\v2\x16.athena.agent.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"@\n" +
	"\rCancelRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x0eCancelResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*?\n" +
	"\fResponseType\x12\f\n" +
	"\bPROGRESS\x10\x00\x12\v\n" +
	"\aPARTIAL\x10\x01\x12\t\n" +
	"\x05FINAL\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\xad\x03\n" +
	"\fAgentService\x12L\n" +
	"\vExecuteTask\x12\x1c.athena.agent.v1.TaskRequest\x1a\x1d.athena.agent.v1.TaskResponse0\x01\x12[\n" +
	"\x0eGetAgentStatus\x12#.athena.agent.v1.AgentStatusRequest\x1a$.athena.agent.v1.AgentStatusResponse\x12R\n" +
	"\tHeartbeat\x12!.athena.agent.v1.HeartbeatRequest\x1a\".athena.agent.v1.HeartbeatResponse\x12O\n" +
	"\fExecuteBatch\x12\x1d.athena.agent.v1.BatchRequest\x1a\x1e.athena.agent.v1.BatchResponse0\x01\x12M\n" +
	"\n" +
	"CancelTask\x12\x1e.athena.agent.v1.CancelRequest\x1a\x1f.athena.agent.v1.CancelResponseB3Z1github.com/athena-workspace/gateway-unified/protob\x06proto3"

var (
	file_proto_agent_service_proto_rawDescOnce sync.Once
	file_proto_agent_service_proto_rawDescData []byte
)

func file_proto_agent_service_proto_rawDescGZIP() []byte {
	file_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_service_proto_rawDesc), len(file_proto_agent_service_proto_rawDesc)))
	})
	return file_proto_agent_service_proto_rawDescData
}

var file_proto_agent_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_agent_service_proto_goTypes = []any{
	(ResponseType)(0),           // 0: athena.agent.v1.ResponseType
	(*TaskRequest)(nil),         // 1: athena.agent.v1.TaskRequest
	(*TaskResponse)(nil),        // 2: athena.agent.v1.TaskResponse
	(*ProgressUpdate)(nil),      // 3: athena.agent.v1.ProgressUpdate
	(*Error)(nil),               // 4: athena.agent.v1.Error
	(*AgentStatusRequest)(nil),  // 5: athena.agent.v1.AgentStatusRequest
	(*AgentStatusResponse)(nil), // 6: athena.agent.v1.AgentStatusResponse
	(*HeartbeatRequest)(nil),    // 7: athena.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),   // 8: athena.agent.v1.HeartbeatResponse
	(*BatchRequest)(nil),        // 9: athena.agent.v1.BatchRequest
	(*BatchResponse)(nil),       // 10: athena.agent.v1.BatchResponse
	(*CancelRequest)(nil),       // 11: athena.agent.v1.CancelRequest
	(*CancelResponse)(nil),      // 12: athena.agent.v1.CancelResponse
	nil,                         // 13: athena.agent.v1.TaskRequest.ContextEntry
	nil,                         // 14: athena.agent.v1.ProgressUpdate.DetailsEntry
	nil,                         // 15: athena.agent.v1.HeartbeatRequest.MetadataEntry
	nil,                         // 16: athena.agent.v1.HeartbeatResponse.MetadataEntry
}
var file_proto_agent_service_proto_depIdxs = []int32{
	13, // 0: athena.agent.v1.TaskRequest.context:type_name -> athena.agent.v1.TaskRequest.ContextEntry
	0,  // 1: athena.agent.v1.TaskResponse.type:type_name -> athena.agent.v1.ResponseType
	3,  // 2: athena.agent.v1.TaskResponse.progress:type_name -> athena.agent.v1.ProgressUpdate
	4,  // 3: athena.agent.v1.TaskResponse.error:type_name -> athena.agent.v1.Error
	14, // 4: athena.agent.v1.ProgressUpdate.details:type_name -> athena.agent.v1.ProgressUpdate.DetailsEntry
	15, // 5: athena.agent.v1.HeartbeatRequest.metadata:type_name -> athena.agent.v1.HeartbeatRequest.MetadataEntry
	16, // 6: athena.agent.v1.HeartbeatResponse.metadata:type_name -> athena.agent.v1.HeartbeatResponse.MetadataEntry
	1,  // 7: athena.agent.v1.BatchRequest.tasks:type_name -> athena.agent.v1.TaskRequest
	0,  // 8: athena.agent.v1.BatchResponse.type:type_name -> athena.agent.v1.ResponseType
	3,  // 9: athena.agent.v1.BatchResponse.progress:type_name -> athena.agent.v1.ProgressUpdate
	4,  // 10: athena.agent.v1.BatchResponse.error:type_name -> athena.agent.v1.Error
	1,  // 11: athena.agent.v1.AgentService.ExecuteTask:input_type -> athena.agent.v1.TaskRequest
	5,  // 12: athena.agent.v1.AgentService.GetAgentStatus:input_type -> athena.agent.v1.AgentStatusRequest
	7,  // 13: athena.agent.v1.AgentService.Heartbeat:input_type -> athena.agent.v1.HeartbeatRequest
	9,  // 14: athena.agent.v1.AgentService.ExecuteBatch:input_type -> athena.agent.v1.BatchRequest
	11, // 15: athena.agent.v1.AgentService.CancelTask:input_type -> athena.agent.v1.CancelRequest
	2,  // 16: athena.agent.v1.AgentService.ExecuteTask:output_type -> athena.agent.v1.TaskResponse
	6,  // 17: athena.agent.v1.AgentService.GetAgentStatus:output_type -> athena.agent.v1.AgentStatusResponse
	8,  // 18: athena.agent.v1.AgentService.Heartbeat:output_type -> athena.agent.v1.HeartbeatResponse
	10, // 19: athena.agent.v1.AgentService.ExecuteBatch:output_type -> athena.agent.v1.BatchResponse
	12, // 20: athena.agent.v1.AgentService.CancelTask:output_type -> athena.agent.v1.CancelResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_agent_service_proto_init() }
func file_proto_agent_service_proto_init() {
	if File_proto_agent_service_proto != nil {
		return
	}
	file_proto_agent_service_proto_msgTypes[1].OneofWrappers = []any{
		(*TaskResponse_Progress)(nil),
		(*TaskResponse_PartialResult)(nil),
		(*TaskResponse_FinalResult)(nil),
		(*TaskResponse_Error)(nil),
	}
	file_proto_agent_service_proto_msgTypes[9].OneofWrappers = []any{
		(*BatchResponse_Progress)(nil),
		(*BatchResponse_FinalResult)(nil),
		(*BatchResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_service_proto_rawDesc), len(file_proto_agent_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_proto_agent_service_proto_depIdxs,
		EnumInfos:         file_proto_agent_service_proto_enumTypes,
		MessageInfos:      file_proto_agent_service_proto_msgTypes,
	}.Build()
	File_proto_agent_service_proto = out.File
	file_proto_agent_service_proto_goTypes = nil
	file_proto_agent_service_proto_depIdxs = nil
}
